🛠️ Refactor Sentieon Joint Call for Beta Prod
kids-first/Kids-First-Sentieon-Joint-Cohort-Genotyping-Workflow pull request #1
Opened 2024-05-03 19:08 UTC by migbro

I've taken the work based off of Haodong and myself from his repo, forked it, and am shaping it into a KF DRC product. I've added documentation on how to use the "easy" workflow and the "advanced," which requires a notebook.

2024-05-03 19:56 UTC, dmiller15 commented on workflow/kf-joint-cohort-call-by-chr-wf.cwl
> +    scatter: [scatter_index]
I think you can just put `interval` and `output_file_name` into the scatter here and avoid having to do the `valueFrom` statements.

2024-05-03 19:58 UTC, dmiller15 commented on workflow/kf-joint-cohort-call-by-chr-wf.cwl
> +    out: [out_name_list, out_intvl_list]
I think you should just put this logic into `fai_subset.cwl`

2024-05-06 18:08 UTC, migbro commented
@dmiller15 refactored a bit as request, new task example here: https://cavatica.sbgenomics.com/u/d3b-bixu/kf-sentieon-join-cohort-genotyping-dev/tasks/cdd2fc6d-8665-4764-a565-ba362a0bdaaf/#

2024-05-06 20:20 UTC, dmiller15 requested changes
Overall, I think more work should be done to clean up the Python notebook. I'm not an expert on making those, but, if it's possible, I think we should have an opening block where users can put in the variable/unique-to-their-situation values then have it be pretty much hands off from there. Like our workflows: "just set these parameters, then we'll do the rest."

2024-05-06 20:20 UTC, dmiller15 commented on README.md
> +Both workflows have limited implementations of the [`GVGFtyper` algo](https://support.sentieon.com/manual/usages/general/#gvcftyper-algorithm) which is part of the [sentieon driver library](https://s
```suggestion
Both workflows have limited implementations of the [`GVGFtyper` algo](https://support.sentieon.com/manual/usages/general/#gvcftyper-algorithm) which is part of the [Sentieon driver library](https://support.sentieon.com/manual/usages/general/#driver-binary).
```

2024-05-06 20:20 UTC, dmiller15 commented on README.md
> +![data service logo](https://github.com/d3b-center/d3b-research-workflows/raw/master/doc/kfdrc-logo-sm.png)
Center align this as well?

2024-05-06 20:20 UTC, dmiller15 commented on README.md
> +The platform has an internal workflow scatter limit of ~2200 files, which means, **if your cohort size is greater than this, it will not run!**.
```suggestion
The platform has an internal workflow scatter limit of ~2200 files, which means, **if your cohort size is greater than this, it will not run!**
```

2024-05-06 20:20 UTC, dmiller15 commented on README.md
> +If your cohort is >2200 samples, but projected to use less than 4TB per split job and chromosome call job, you can use this.
> projected to use less than 4TB per split job and chromosome call job

How can I make this calculation?

2024-05-06 20:20 UTC, dmiller15 commented on README.md
> +## [Easy Cohort Calling Workflow](docs/KF_COHORT_JG_SINGLE_WF.md)
Not sure if I like the "Easy" vs "Advanced" descriptions. Like if your input is smaller than 2200 files, you should only over use the "Easy" pipeline. There's no benefit to using the "Advanced" pipeline.

2024-05-06 20:20 UTC, dmiller15 commented on docs/KF_COHORT_JG_SINGLE_WF.md
> +![data service logo](https://github.com/d3b-center/d3b-research-workflows/raw/master/doc/kfdrc-logo-sm.png)
Center align?

2024-05-06 20:20 UTC, dmiller15 commented on docs/KF_COHORT_JG_SINGLE_WF.md
> +This workflow is takes a set of gVCF files from a desired cohort and an indexed FASTA reference to create a joint-called cohort.
```suggestion
This workflow is takes a set of gVCFs and an indexed reference FASTA to create a joint-called cohort VCF.
```

2024-05-06 20:20 UTC, dmiller15 commented on docs/KF_COHORT_JG_SINGLE_WF.md
> +It will split the input gVCF files, using up to AWS 60 c5.12xlarge instances, and stack 12 gVCF files per instance to split them by chromosome.
```suggestion
The input gVCFs are sharded by chromosome. To accelerate the process, the sharding is done across 60 instances, each of which is processing 12 files at a time.
```

2024-05-06 20:20 UTC, dmiller15 commented on docs/KF_COHORT_JG_SINGLE_WF.md
> +Then, all of the gVCF chromosome fragments are split, one instance per chromosome, to a Sentieon GVCFtyper job.
```suggestion
Next, gVCF shards that share a common chromosome are gathered and passed to Sentieon GVCFtyper, producing one joint VCF per chromosome.
```

2024-05-06 20:20 UTC, dmiller15 commented on docs/KF_COHORT_JG_SINGLE_WF.md
> + - `joint_called_by_chr_vcf`: Array of joint-called files split by chromosome
Shouldn't we merge these files in the end?

2024-05-06 20:20 UTC, dmiller15 commented on docs/KF_COHORT_JG_SINGLE_WF.md
> +Cohort size is simple - **it must be less than ~2200 samples** to run, otherwise the platform will will quit immediately with error:
These are getting smashed together
```suggestion
 - File input size

Cohort size **must be less than ~2200 samples** to run, otherwise the platform will will quit immediately with error:
```

2024-05-06 20:20 UTC, dmiller15 commented on docs/KF_COHORT_JG_SINGLE_WF.md
> +This can be increased to 4TB; if you still run out of space, consider a smaller cohort if possible, limiting sites, or a different platform (sorry!)
Not sorry...
```suggestion
CAVATICA instances, by default, start with 1TB of EBS storage. The storage can be increased through the `Execution Settings` all the way up to 4TB.
If 4TB is insufficient to process your cohort, contact CAVATICA support for assistance. Alternatively, try refining the cohort or limiting the sites of interest.
```

2024-05-06 20:20 UTC, dmiller15 commented on docs/KF_COHORT_JG_SINGLE_WF.md
> + - `input_vcf`: Indexed gVCF files to perform cohort calling on. It's recommended that the [GATK Haplotyper caller workflow](https://cavatica.sbgenomics.com/public/apps/cavatica/apps-publisher/kfdrc-
For people...like me...that don't keep up with what every initialism means
```suggestion
 - `input_vcf`: Indexed gVCF files to perform cohort calling on. It's recommended that the [GATK Haplotyper caller workflow](https://cavatica.sbgenomics.com/public/apps/cavatica/apps-publisher/kfdrc-gatk-haplotypecaller-workflow) or [Sentieon equivalent](https://cavatica.sbgenomics.com/public/apps/cavatica/apps-publisher/kfdrc_sentieon_gvcf_wf) has been used to generate each of these inputs. If gVCFs were obtained from Gabriella Miller Kids First (GMKF), it will meet this recommendation.
```

2024-05-06 20:20 UTC, dmiller15 commented on docs/KF_COHORT_JG_SINGLE_WF.md
> + - `sentieon_license`: Sentieon license server host and port in format 0.0.0.0:0000. Is set by default by the workflow, but can be changed if circumstances require it.
```suggestion
 - `sentieon_license`: Sentieon license server host and port in format `0.0.0.0:0000`. Is set by default by the workflow, but can be changed if circumstances require it.
```

2024-05-06 20:20 UTC, dmiller15 commented on docs/KF_COHORT_JG_SINGLE_WF.md
> + - `fai_subset`: Parameter used to set which chromosome are to be used based ion the fasta index file. It's generally recommended to use only chr1-22,X,Y (some would say canonical), therefore this pa
```suggestion
 - `fai_subset`: Parameter used to set which chromosome are to be used based on the FASTA index file. It's generally recommended to use the canonical chromosomes (chr1-22,X,Y). By default, this parameter is set to `24` to capture those first 24 chromosomes of the FASTA index.
```

2024-05-06 20:20 UTC, dmiller15 commented on docs/KF_COHORT_JG_SINGLE_WF.md
> +   - EBS storage: `2048` m up to `4096`
```suggestion
   - EBS storage: `2048` up to `4096`
```

2024-05-06 20:20 UTC, dmiller15 commented on docs/KF_NOTEBOOK_JG_WORKFLOW.md
> +Due to platform limitations, running the easier workflow may not be feasible when cohorts exceed 200 samples, due to scatter job size limitations.
200 samples? Not 2000?

2024-05-06 20:20 UTC, dmiller15 commented on docs/KF_NOTEBOOK_JG_WORKFLOW.md
> +[This notebook](../workflow/kf-joint-cohort-call-advanced-setup.ipynb) can be used to set up the split by chromosome jobs, in which N jobs are created to split X files per instance, depending on yor
```suggestion
[This notebook](../workflow/kf-joint-cohort-call-advanced-setup.ipynb) can be used to set up the split by chromosome jobs, in which N jobs are created to split X files per instance, depending on your math.
```

2024-05-06 20:20 UTC, dmiller15 commented on docs/KF_NOTEBOOK_JG_WORKFLOW.md
> +Then with sensible tagging and sorting, the outputs from these jobs can be reliable pass to the Sentieon GVCFtyper to create the final product.
```suggestion
Then with sensible tagging and sorting, the outputs from these jobs can be reliably passed to the Sentieon GVCFtyper to create the final product.
```

2024-05-06 20:20 UTC, dmiller15 commented on docs/KF_NOTEBOOK_JG_WORKFLOW.md
> +In the end, you'll want to delete all files with the `INTERMEDIATE` tag to avoid excessive storage costs on files that are likely cheaper to regenerate as needed than store indefinitely
```suggestion
In the end, you'll want to delete all files with the `INTERMEDIATE` tag to avoid excessive storage costs. These files can be quickly and cheaply regenerated, as needed.
```

2024-05-06 20:20 UTC, dmiller15 commented on workflow/kf-joint-cohort-call-advanced-setup.ipynb
You recommend chr1-22,X,Y,M here. The other documentation doesn't include M

2024-05-07 13:11 UTC, migbro commented on docs/KF_COHORT_JG_SINGLE_WF.md
> + - `joint_called_by_chr_vcf`: Array of joint-called files split by chromosome
Eh, nah, most people seem to like to operate by chromosome I think. The merge step is a slow, single-threaded step that we can consider making optional...I took it out to just have a "this is what I ended up doing" workflow

2024-05-07 16:00 UTC, migbro commented
Ok, I refactored the notebook to have all needed variables set up front. Split jobs finished here:
https://cavatica.sbgenomics.com/u/d3b-bixu/kf-sentieon-join-cohort-genotyping-dev/tasks?search=Split%20GVCF%20by%20chr%20set
Joint jobs finished here: https://cavatica.sbgenomics.com/u/d3b-bixu/kf-sentieon-join-cohort-genotyping-dev/files/#q?search=CBTN-TEST_

2024-05-08 15:30 UTC, dmiller15 approved these changes
I slacked you a small refactor for one of the ipynb steps but otherwise looks good to me

2024-05-09 15:07 UTC, wongjessica93 commented on docs/KF_COHORT_JG_SINGLE_WF.md
> +This workflow is takes a set of gVCFs and an indexed reference FASTA to create a joint-called cohort VCF.
Typo - 
This workflow takes a set of gVCFs and an indexed reference FASTA to create a joint-called cohort VCF.

2024-05-09 15:18 UTC, wongjessica93 commented on docs/KF_NOTEBOOK_JG_WORKFLOW.md
> +Due to platform limitations, running the Preferred workflow may not be feasible when cohorts exceed 2200 samples, due to scatter job size limitations.
Idk if this has an obvious answer, but what should users do if the cohort is > 2200? Should they break up the samples into smaller cohorts and do multiple run

2024-05-09 15:30 UTC, wongjessica93 approved these changes

2024-05-09 15:37 UTC, migbro commented on docs/KF_NOTEBOOK_JG_WORKFLOW.md
> +Due to platform limitations, running the Preferred workflow may not be feasible when cohorts exceed 2200 samples, due to scatter job size limitations.
Oh, well, it's to run this one up to a certain point, probably like 3500. Lemme double check, I put some hints elsewhere, but you get to a point where, for this platform, you'd have to either use smaller cohorts (but sometimes that's just not feasible as perhaps all samples have to be run together and can't be further sub-categorized), or focus on certain regions, which this workflow does not do. That might be a future update

2024-05-09 15:53 UTC, merged